// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetMessagesMessagesGetData, GetMessagesMessagesGetResponse, SendSendPostData, SendSendPostResponse, SendSendPostError } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Messages
 */
export const getMessagesMessagesGet = <ThrowOnError extends boolean = false>(options?: Options<GetMessagesMessagesGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMessagesMessagesGetResponse, unknown, ThrowOnError>({
        url: '/messages',
        ...options
    });
};

/**
 * Send
 */
export const sendSendPost = <ThrowOnError extends boolean = false>(options: Options<SendSendPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<SendSendPostResponse, SendSendPostError, ThrowOnError>({
        url: '/send',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};