// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetMessagesMessagesGetData, GetMessagesMessagesGetResponse, SendSendPostData, SendSendPostResponse, SendSendPostError, GetBranchesRepoAccountRepoNameBranchesGetData, GetBranchesRepoAccountRepoNameBranchesGetResponse, GetBranchesRepoAccountRepoNameBranchesGetError, GetRepoRepoAccountRepoNameBranchGetData, GetRepoRepoAccountRepoNameBranchGetResponse, GetRepoRepoAccountRepoNameBranchGetError, GetFileRepoAccountRepoNameBranchPathGetData, GetFileRepoAccountRepoNameBranchPathGetResponse, GetFileRepoAccountRepoNameBranchPathGetError } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Messages
 */
export const getMessagesMessagesGet = <ThrowOnError extends boolean = false>(options?: Options<GetMessagesMessagesGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMessagesMessagesGetResponse, unknown, ThrowOnError>({
        url: '/messages',
        ...options
    });
};

/**
 * Send
 */
export const sendSendPost = <ThrowOnError extends boolean = false>(options: Options<SendSendPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<SendSendPostResponse, SendSendPostError, ThrowOnError>({
        url: '/send',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Branches
 */
export const getBranchesRepoAccountRepoNameBranchesGet = <ThrowOnError extends boolean = false>(options: Options<GetBranchesRepoAccountRepoNameBranchesGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetBranchesRepoAccountRepoNameBranchesGetResponse, GetBranchesRepoAccountRepoNameBranchesGetError, ThrowOnError>({
        url: '/repo/{account}/{repo_name}/branches',
        ...options
    });
};

/**
 * Get Repo
 */
export const getRepoRepoAccountRepoNameBranchGet = <ThrowOnError extends boolean = false>(options: Options<GetRepoRepoAccountRepoNameBranchGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetRepoRepoAccountRepoNameBranchGetResponse, GetRepoRepoAccountRepoNameBranchGetError, ThrowOnError>({
        url: '/repo/{account}/{repo_name}/{branch}',
        ...options
    });
};

/**
 * Get File
 */
export const getFileRepoAccountRepoNameBranchPathGet = <ThrowOnError extends boolean = false>(options: Options<GetFileRepoAccountRepoNameBranchPathGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetFileRepoAccountRepoNameBranchPathGetResponse, GetFileRepoAccountRepoNameBranchPathGetError, ThrowOnError>({
        url: '/repo/{account}/{repo_name}/{branch}/{path}',
        ...options
    });
};