// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    role: string;
    content: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type GetMessagesMessagesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/messages';
};

export type GetMessagesMessagesGetResponses = {
    /**
     * Successful Response
     */
    200: Array<Message>;
};

export type GetMessagesMessagesGetResponse = GetMessagesMessagesGetResponses[keyof GetMessagesMessagesGetResponses];

export type SendSendPostData = {
    body: Array<Message>;
    path?: never;
    query?: never;
    url: '/send';
};

export type SendSendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendSendPostError = SendSendPostErrors[keyof SendSendPostErrors];

export type SendSendPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type SendSendPostResponse = SendSendPostResponses[keyof SendSendPostResponses];